### ISSUE TITLE
Questions about the settings in mmdet3d version

### ISSUE THREAD

**Issue by gujiaqivadin** [saic-vul/imvoxelnet#10]
Hello, saic-vul!
   Thanks for your excellent work imvoxelnet!  I am looking into the realization in mmdet3d official repo of kitti dataset, and I am curious about anchor_generator settings in imvoxelnet_kitti-3d-car.py. I found that two anchor-generator are defined in this file, one for genrating anchors and the other for generating voxel-wise features. But these two settings are different in ranges(height dimensions). I want to know why it is different. Thanks a lot!

**Comment by filaPro** [comment]
Hi, @gujiaqivadin ,
Sure, these 2 anchor generators are the same for `x` and `y` axis and differs in `z`. The thing is `Anchor3DHead` is based on `2D` convolutions, so `Anchor3DHead.anchor_generator` indeed returns `2D` anchors. Which means that `z_min = z_max` and this 2 numbers are meaningless. However for voxel generation we utilize the range from -3 to +1 meters for `z` axis.

**Comment by gujiaqivadin** [comment]
OK, it solves my questions well. Thx!
