### ISSUE TITLE
about create_data.py script?

### ISSUE THREAD

**Issue by rockywind** [saic-vul/imvoxelnet#12]
Thanks for sharing the codes. I met the error, but I never modified anything.
The script is :
`python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti`
The result is:
 `Traceback (most recent call last):
  File "tools/create_data.py", line 4, in <module>
    from tools.data_converter import indoor_converter as indoor
ModuleNotFoundError: No module named 'tools.data_converter'`

**Comment by filaPro** [comment]
Hi @rockywind ,
I think it's just about your installation as `data_converter` directory is definitely in `tools` directory. Can you try with updated PYTHONPATH ? Ex. : `PYTHONPATH=./ python tools/create_data.py ...`

**Comment by rockywind** [comment]
Thanks a lot. @filaPro

**Comment by rockywind** [comment]
Thanks for your help on the previous issue.
I met another issue.
`(imvoxelnet) zizhang.wu@shaxbw06:/newnfs/zzwu/08_3d_code/imvoxelnet02$ python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitt
Traceback (most recent call last):
  File "tools/create_data.py", line 8, in <module>
    from tools.data_converter import nuscenes_monocular_converter
ImportError: cannot import name 'nuscenes_monocular_converter' from 'tools.data_converter' (/newnfs/zzwu/08_3d_code/imvoxelnet02/mmdetection3d/tools/data_converter/__init__.py)
`

**Comment by filaPro** [comment]
I've tried the code a couple of days ago, `python tools/create_data.py` was fine. Can you please try with our [Dockerfile](https://github.com/saic-vul/imvoxelnet/blob/master/docker/Dockerfile)?

**Comment by rockywind** [comment]
Thank you a lot. I'm unfamiliar with Docker. Can you give me a hand with how to build a Docker?

**Comment by filaPro** [comment]
Hi @rockywind ,

It's not that simple to explain what Docker is here. It's better to start [here](https://docs.docker.com/get-started/). After installation you simply run:
```
cd docker
docker build -t imvoxelnet ./
docker run -ti imvoxelnet
```

**Comment by rockywind** [comment]
Thanks a lot. I

**Comment by HuangCongQing** [comment]
You can try: 
```
export PYTHONPATH=$PYTHONPATH:$PWD
```
