### ISSUE TITLE
Install instruction

### ISSUE THREAD

**Issue by chetanmreddy** [saic-vul/imvoxelnet#13]
Hello @filaPro 

I am trying to run your trained models on KITTI dataset.

While setting up the dependencies, I see that  the instructions provided [here](https://github.com/saic-vul/imvoxelnet/blob/master/docs/install.md) and [here](https://github.com/saic-vul/imvoxelnet/blob/master/docker/Dockerfile) are different. Specifcally how we install mmdetection3d.

Can you please help which one you have used?

Thank you

**Comment by filaPro** [comment]
Hi @chetanmreddy ,
They are quite similar except of installing [rotated_iou](https://github.com/lilanxiao/Rotated_IoU). However I recommend to follow our [Dockerfile](https://github.com/saic-vul/imvoxelnet/blob/master/docker/Dockerfile).
