### ISSUE TITLE
Question about the resize in preprocessing pipeline of KITTI

### ISSUE THREAD

**Issue by gujiaqivadin** [saic-vul/imvoxelnet#14]
Hello, saic-vul!
     Thanks for your great work imvoxelnet. I am curious about the resize operation as it resize images of KITTI into ((1173, 352), (1387, 416)), which is a little different from other kitti mono3d detection methods. The common size of kitti is like (1280, 384) or (1242, 375). I wonder why you choose the strange settings for resize. Thanks a lot !

**Comment by filaPro** [comment]
Hi @gujiaqivadin ,
As you can see for testing we [resize](https://github.com/saic-vul/imvoxelnet/blob/master/configs/imvoxelnet/imvoxelnet_kitti.py#L100) the image to the common size of `(1280, 384) `.
However the training resize that you mentioned is just the same  `(1280, 384) ` with a small scale augmentation. You can check the [Resize](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L26) class in `mmdetection` for better unserstanding of this range.

**Comment by gujiaqivadin** [comment]
Thanks a lot!
