### ISSUE TITLE
Why do I need to download and use KITTI velodyne data?

### ISSUE THREAD

**Issue by chetanmreddy** [saic-vul/imvoxelnet#18]
Hello @filaPro 

I was reading your paper and trying to implement your method on an RGB dataset that I have collected.

While trying to test your code, it looks like you also need KITTI Velodyne data to be downloaded.
Does your method use lidar point cloud or else you are using point cloud dataset for some other purpose.

Thank you for sharing the code and your help.

**Comment by filaPro** [comment]
Hi @chetanmreddy ,

`ImVoxelNet` uses only a single `rgb` image and a pose for `KITTI` dataset as can be seen in our [KittiMultiViewDataset](https://github.com/saic-vul/imvoxelnet/blob/master/mmdet3d/datasets/kitti_monocular_dataset.py#L10). 

The [tools/create_data.py](https://github.com/saic-vul/imvoxelnet/blob/master/tools/create_data.py) script for `KITTI` is simply copied from `mmdetection3d`, so it also processes `Velodyne` data. In our case it is not used after this step. You can probably comment all point cloud preprocessing in [tools/data_converter/kitti_converter.py](https://github.com/saic-vul/imvoxelnet/blob/master/tools/data_converter/kitti_converter.py) if you don't want to download this data.

**Comment by chetanmreddy** [comment]
Thank you @filaPro  for your kind help. That clears my question.

I am facing an issue after doing the above steps suggested.

![12](https://user-images.githubusercontent.com/18630132/125354603-d78d1600-e318-11eb-8ce8-8a6bf46529f0.png)


It looks like the create_groundtruth_database is using the kitti_dataset.py instead of kitti_monocular_dataset.py

Do you know why it could be happening?

Thank you again for your help

**Comment by chetanmreddy** [comment]
Never mind. I got it figured out. Thank you

**Comment by chetanmreddy** [comment]
Hi @filaPro 

I am getting the following error while training:

![13](https://user-images.githubusercontent.com/18630132/125513368-f3a69a3d-077d-4774-b9ef-ece5fd2deecf.png)


My image size is 1024 X 1024. I haven't changed anything in the config file.
Can you please help me?
Thank you

**Comment by filaPro** [comment]
Can you please provide more info? Are you training on KITTI? Which config file are you using? However, the default size for KITTI is 1280 x 384, not 1024 x 1024. Also the full log file might be helpful.

**Comment by chetanmreddy** [comment]
My bad, I forgot to mention that I am training on my custom dataset which I have prepared according to kiiti format.

The size of my images is 1024 in my dataset.

I am using the configs/imvoxelnet/imvoxelnet_kitti.py for config file.

I am attaching my full log file from work_dirs. please find here
[20210713_184140.log](https://github.com/saic-vul/imvoxelnet/files/6811509/20210713_184140.log)

**Comment by filaPro** [comment]
Looks like some bug with `RandomFlip` transform. I can have a look tomorrow. For now you can probably remove `dict(type='RandomFlip')` from the config.

Btw, were you able to train a model on KITTI?

**Comment by chetanmreddy** [comment]
Yes I was able to train on KITTI first.

Do you think it has something to do with the image size? I see that there are few values(eg img_scale) set for kitti in the config file.

Thanks for your suggestion.I will try that

**Comment by filaPro** [comment]
You can check `mmdet/datasets/pipelines/transforms.py`, line 440, mentioned in your traceback. It is about `flip_ratio=None` for `RandomFlip.__init__`. Probably `flip_ratio` should be `0.5`. However it worked somehow on KITTI...

**Comment by filaPro** [comment]
Don't quite understand how you were able to train on KITTI, as I'm getting the same bug there. Fixes `flip_ratio` from `None` to `0.5` in [5fb7d07](https://github.com/saic-vul/imvoxelnet/commit/5fb7d0758eb0c78717a0dd03787808ef6bf45331).

**Comment by chetanmreddy** [comment]
I think I was training your method from mmdet3d repository instead of yours a few days ago. [LINK](https://github.com/open-mmlab/mmdetection3d/issues/694#issue-935334692)

May be that's why I didn't encounter this issue back then

**Comment by chetanmreddy** [comment]
Hi @filaPro I am trying to understand your visualization part of the code while testing. It works completely fine for me.

But when I was looking at the code I see that the `show_results` function is not implemented in `mmdet3d/models/detectors/imvoxelnet.py`

While running this command `python tools/test.py configs/imvoxelnet/imvoxelnet_kitti.py \
    work_dirs/imvoxelnet_kitti/latest.pth --show \
    --show-dir work_dirs/imvoxelnet_kitti`  which `show_results` is being called?

Thank you for your help

**Comment by filaPro** [comment]
We overwrite `show` method of all monocular and multiview datasets [here](https://github.com/saic-vul/imvoxelnet/blob/master/mmdet3d/datasets/dataset_wrappers.py#L109).
