### ISSUE TITLE
can i use imvoxelnet to realize multiview 3D object detection demo? 

### ISSUE THREAD

**Issue by jasmine202106** [saic-vul/imvoxelnet#19]
Hi, author,

i want to realize one demo, its input is two or three images taken by camera from different views of one object and the output is 3D bounding boxes of the object.
can imvoxelnet realize this function? if OK, can you tell how to realize it using imvoxelnet? 

thanks very much.

**Comment by filaPro** [comment]
Hi @jasmine202106 ,

If I understand you correctly, you are not going to train a model on your data, just to inference one of our models. For indoor scenes we provide pretrained model on SUN RGB-D and ScanNet data. ScanNet model is ready for multi-view detection and SUN RGB-D  model is for monocular detection. However both datasets provide camera intrinsic and extrinsic matrices. Can guess, that you don't have this matrices for your camera.

Without camera poses you can check only our monocular SUN RGB-D model for Total3DUnderstanding benchmark. Also you need to provide some fake intrinsic matrix for is.

**Comment by rockywind** [comment]
Thanks for sharing the codes. 
Its input is six images taken by the surrounding camera and output 3D object in BEV space in inference mode. Are there any function in imvoxelnet to do that?

**Comment by filaPro** [comment]
Hi @rockywind ,

As I said before, you can run ScanNet pretrained model: 
```
python tools/test.py configs/imvoxelnet/imvoxelnet_scannet.py \
    work_dirs/imvoxelnet_scannet/latest.pth --show \
    --show-dir work_dirs/imvoxelnet_scannet
```
With this command as an example were generated images in our [readme](https://github.com/saic-vul/imvoxelnet#example-detections).

However, you need camera poses for all your six images and camera intrinsics matrix. You can save all of this to ScanNet format  or refactor `ScanNetDataset`. Also your object of interest must be one of the ScanNet [categories](https://github.com/saic-vul/imvoxelnet/blob/master/configs/imvoxelnet/imvoxelnet_scannet.py#L43). And the last thing, we don't predict rotation angle for ScanNet dataset, the bounding box is axis-aligned (parallel to room walls).

**Comment by rockywind** [comment]
Yes, thanks a lot!
