### ISSUE TITLE
it seems many false bounding boxes for test result for scannet dataset.

### ISSUE THREAD

**Issue by jasmine202106** [saic-vul/imvoxelnet#22]
I run the below instruction for scannet dataset test. but the result seems have many false bounding boxes, or the result is correct?
I set score_thr in configs to 0.15.
I used SensReader c++ script to prepare scannet data, and use
$python tools/create_data.py scannet_monocular --root-path ./data/scannet --out-dir ./data/scannet --extra-tag scannet
to generate scannet_infos_train.pkl and scannet_infos_val.pkl

$python tools/test.py configs/imvoxelnet/imvoxelnet_scannet.py ./data/checkpoints/scannet.pth --show --show-dir ./data/scannet/show-dir/
Use load_from_local loader
[                                                  ] 0/6, elapsed: 0s, ETA:/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py:3121: UserWarning: Default upsampling behavior when mode=trilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6/6, 0.6 task/s, elapsed: 11s, ETA:     0s

![frame-002646 color](https://user-images.githubusercontent.com/85660366/126598421-897838a4-ba23-41c6-a7b3-e4cd4a4bea51.png)

**Comment by filaPro** [comment]
Can you please check with 0.20 ore 0.25?

**Comment by filaPro** [comment]
Have checked with `score_thr=0.20` on `scene0086_00` from our [README](https://github.com/saic-vul/imvoxelnet/blob/master/README.md). Looks fine.

**Comment by jasmine202106** [comment]
sorry, above is the result of score_thr=0.0.

this is the result of score_thr=0.15:
![frame-000706 color](https://user-images.githubusercontent.com/85660366/126601015-fac3fcea-fb10-4a28-b9d8-fe64c173a9c3.png)

this is the result of score_thr=0.25:
![frame-000706 color](https://user-images.githubusercontent.com/85660366/126600432-339583f6-5326-47a9-a4f6-a0603b107695.png)

Can these results mean i run the code correctly?

**Comment by filaPro** [comment]
Yes, looks fine. A couple of chairs are detected correctly.

**Comment by jasmine202106** [comment]
OK, very thanks.
