### ISSUE TITLE
NMS doesn‘t seem to work. The visualization of 3D boundingbox in SUNRGBD dataset contains lots of overlapped boxes.

### ISSUE THREAD

**Issue by XIDIANPQZ** [saic-vul/imvoxelnet#24]
![0000001](https://user-images.githubusercontent.com/47958632/130756629-5f783516-5933-4a59-84c1-5fd3707d4309.png)

**Comment by filaPro** [comment]
Hi @XIDIANPQZ ,

Can you please try with `score_thr=0.15` or more as advised in our readme?

**Comment by XIDIANPQZ** [comment]
> Hi @XIDIANPQZ ,
> 
> Can you please try with `score_thr=0.15` or more as advised in our readme?

Thanks. I have tried with different score_thr. The network with high score_thr only detects a bed, but still produces many overlapped boxes

**Comment by filaPro** [comment]
![0000289](https://user-images.githubusercontent.com/6030962/130770385-dd32e9da-913e-487d-af83-e0634c0fce9f.png)
I've tried now this config and model with `score_thr=0.15`. Looks fine. Not too much overlapping boxes. However it's probably strange why 2 blue boxes appear after nms.

> During the visualization, "Error!" is printed when the 46 line of "mmdet3D/ops/iou3d/iou3d_utils.py" is passed.

Can you paste full traceback? I'm not facing any issues. How you were able to run visualization with the error?

**Comment by XIDIANPQZ** [comment]
```
(open-mmlab) lab@lab:~/0pqz/imvoxelnet-master$ python tools/test.py configs/imvoxelnet/imvoxelnet_total_sunrgbd_top27.py '/home/lab/0pqz/imvoxelnet-master/checkpoints/20210808_005013.pth' --show --show-dir work_dirs/imvoxelnet_total_sunrgbd_top27
[                                                  ] 0/50, elapsed: 0s, ETA:/home/lab/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py:3063: UserWarning: Default upsampling behavior when mode=trilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
[>                                                 ] 1/50, 1.1 task/s, elapsed: 1s, ETA:    46s
Error!
Error!
[>>                                                ] 2/50, 1.8 task/s, elapsed: 1s, ETA:    26s
Error!
[>>>                                               ] 3/50, 2.4 task/s, elapsed: 1s, ETA:    19s
Error!
Error!
[>>>>                                              ] 4/50, 2.9 task/s, elapsed: 1s, ETA:    16s
Error!
[>>>>>                                             ] 5/50, 3.3 task/s, elapsed: 2s, ETA: 
```
The 'Error' is printed after each sample completes inference. When I debug the code step by step, I find that the cause is in  "mmdet3D/ops/iou3d/iou3d_utils.py".

I am not sure if this is caused by the version of Sofaware.

**Comment by XIDIANPQZ** [comment]
This error may be from iou3d.cpp.
`if (cudaSuccess != cudaGetLastError())  printf("Error!\n")`
However, I don't know the reasons.

**Comment by filaPro** [comment]
Never met this before. This message is produced by `cuda` code [here](https://github.com/saic-vul/imvoxelnet/blob/master/mmdet3d/ops/iou3d/src/iou3d.cpp#L144). I think this is caused by your `cuda` version `11.0`, however we use `10.1` in our [Dockerfile](https://github.com/saic-vul/imvoxelnet/blob/master/docker/Dockerfile). Looks like `mmdetection3d` is not ever tested with `11.0`.

**Comment by XIDIANPQZ** [comment]
Will this error cause NMS to fail?

**Comment by filaPro** [comment]
Yes it can be the reason. Can you please try with `torch==1.6.0` and `cuda10.1`?

**Comment by XIDIANPQZ** [comment]
Thank you. I will try the suggest version again.
