### ISSUE TITLE
Question about sunrgbd_total.py

### ISSUE THREAD

**Issue by XIDIANPQZ** [saic-vul/imvoxelnet#25]
During the process of dealing with sunrgbd data, the line 27-43 of sunrgbd_total.py contains many coordinates trasformation. It is hard to understand the whole process. Can you please provide some plots to explain it?
```
    for image_data in data['images']:
        r = np.array(image_data['rot_mat'])
        yaw = np.arctan(-r[2][0] / r[0][0])
        pitch = np.arctan(r[1][0] / np.sqrt(r[0][0] ** 2 + r[2][0] ** 2))
        roll = np.arctan(-r[1][2] / r[1][1])
        assert(np.isclose(yaw, 0))

        # follow Total3DUnderstanding
        t = np.array([[0., 0., 1.], [0., -1., 0.], [-1., 0., 0.]])
        r = t @ r.T
        # follow DepthInstance3DBoxes
        r = r[:, [2, 0, 1]]
        r[2] *= -1
        # invert SUNRGBDMonocularDataset._get_matrices
        r = r.T
        r[:, 1] = -1 * r[:, 1]
        r[:, [1, 2]] = r[:, [2, 1]]
```

**Comment by filaPro** [comment]
Hi @XIDIANPQZ ,

Agree that this place is very confusing. All these lines are only about the transformation of the extrinsic camera matrix. Its representation is different in 3 places: 

1. `Total3DUnderstanding` with their parametrization with `yaw=0`. You can probably check their [code](https://github.com/yinyunie/Total3DUnderstanding) or [paper](https://arxiv.org/abs/2002.12212) for more details.

2. Original matrix from `SUN RGB-D` authors.

3. Our coordinate system for all 4 indoor and outdoor datasets. 

So, with this hacks we transform 1. to 3. Of course, it can be rewritten much shortly.

**Comment by XIDIANPQZ** [comment]
Thanks，@filaPro ，I have checked the paper and code of “Total3DUnderstanding”. The coordinate system belongs to toward-up-right.
![image](https://user-images.githubusercontent.com/47958632/131596201-a277d41c-c05c-4e73-b0ca-7cae6de8f30a.png)
For SUN RGB-D and your methods, I didn't find the similar picture. 
I would be grateful if you could provide a schematic diagram.

**Comment by filaPro** [comment]
I think as we use `DepthInstance3DBoxes` for `SUN RGB-D`, the coordinate system is described in [its](https://github.com/saic-vul/imvoxelnet/blob/master/mmdet3d/core/bbox/structures/depth_box3d.py#L10) docstring.

**Comment by XIDIANPQZ** [comment]
Thank you
