### ISSUE TITLE
Why not use conv3D  instead of sparse conv3D?

### ISSUE THREAD

**Issue by rockywind** [saic-vul/imvoxelnet#27]
Hi,
As we know, sparse conv3d is popular in the 3D detection pipeline, such as CenterPoint, PV-RCNN, and so on.
Why do we use  normal conv3D   instead of sparse conv3d.

**Comment by filaPro** [comment]
Hi @rockywind ,

I agree that sparse 3d convolutions are better for 3d object detection as they require much less memory and time. However, for multi-view 3d detection we first need to aggregate the representations from multiple RGB images. In our case this aggregation ends with a dense (nos sparse) voxel volume representation. Consequently we process this volume with dense (not sparse) 3d convolutions.

You can feel free to share the ideas how to make the 3d voxel volume representation sparse. However I think if you have a really good one it can be a great idea for your next paper :)

**Comment by rockywind** [comment]
Yes, I see.
Thank you for your help!
