### ISSUE TITLE
Visualize Detection in Bird Eye View (BEV)

### ISSUE THREAD

**Issue by chuong98** [saic-vul/imvoxelnet#28]
Hi, Thanks for the package.

I have a dummy question: 
Is it possible to visualize the detected results from ImVoxel in BEV for Kitti/NuScene  dataset?
If yes, can you give us a hint how to do it.
Thank you.

**Comment by filaPro** [comment]
Hi @chuong98 ,

Unfortunately we don't have such a visualization. We only support visualization on image plane. However you can simply overwrite our [show](https://github.com/saic-vul/imvoxelnet/blob/master/mmdet3d/datasets/dataset_wrappers.py#L109) function. Just take 4 corners out of 8.

**Comment by chuong98** [comment]
Thank you.
