### ISSUE TITLE
transformation in 'create_nuscenes_monocular_infos'

### ISSUE THREAD

**Issue by Jiayi719** [saic-vul/imvoxelnet#31]
Hello, I try to understand the transformation you do on 'tmp_box' in the following code:
[https://github.com/saic-vul/imvoxelnet/blob/master/tools/data_converter/nuscenes_monocular_converter.py#L108-L114](url)
But I really couldn't make it. Can you explain the insight of this transformation? Thank you.

**Comment by filaPro** [comment]
Hi @Jiayi719 ,

Looks like this function generates `monocular_infos` and `multi_view_infos`. The code you mentioned is only connected with `monocular_infos`. However it is not used anywhere, we only use `nuscenes_multi_view_infos_train.pkl` and `nuscenes_multi_view_infos_val.pkl` in the `NuScenesMultiViewDataset`.

Does this answer help you?

**Comment by Jiayi719** [comment]
Then how ccould we get gt boxes from **nuscenes_multi_view_infos_train.pkl** and **nuscenes_multi_view_infos_val.pkl** ?

**Comment by filaPro** [comment]
I'm very sorry for this mess. This is also related to your next issue. Can you please try the original `nuscenes_infos_train.pkl` from `tools/nuscenes_converter.py`? Looks like current version of code is ready for loading this file. And we can simply ignore `nuscenes_multi_view_infos_train.pkl`, `nuscenes_monocular_infos_train.pkl` and `tools/nuscenes_monocular_converter.py`.

**Comment by Jiayi719** [comment]
Yes, you are right. I have generated nuscenes_infos_train.pkl and nuscenes_infos_val.pkl by running the following command:
> python tools/create_data.py nuscenes --version v1.0-mini --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes
And indeed I succeed to run test on this two pkl files by:

> python tools/test.py configs/imvoxelnet/imvoxelnet_nuscenes.py work_dirs/imvoxelnet_nuscenes/20210505_131108.pth --show --show-dir work_dirs/imvoxelnet_nuscenes

But I wonder this process execute multi-view detection or just execute detection on each camera image respectively?

**Comment by filaPro** [comment]
It should be multi-view. You can check that 6 images per scene are loaded [here](https://github.com/saic-vul/imvoxelnet/blob/master/mmdet3d/datasets/pipelines/multi_view.py#L24)  and then processed [here](https://github.com/saic-vul/imvoxelnet/blob/master/mmdet3d/models/detectors/imvoxelnet.py#L48).

**Comment by filaPro** [comment]
> Yes, you are right. I have generated nuscenes_infos_train.pkl and nuscenes_infos_val.pkl by running the following command:

Removed `nuscenes_monocular` from README in [3512e89](https://github.com/saic-vul/imvoxelnet/commit/3512e89ca98e48aebb21a4c9e9fbe5037220b3a4).

**Comment by Jiayi719** [comment]
When 
![n008-2018-08-01-15-16-36-0400__CAM_BACK__1533151608037558](https://user-images.githubusercontent.com/16137282/143973103-d1dd36c8-fd23-49b0-a336-98d3aeae7a9b.png)

**Comment by Jiayi719** [comment]
I have seen this [(https://github.com/saic-vul/imvoxelnet/blob/master/configs/imvoxelnet/imvoxelnet_nuscenes.py#L99-L110)](url) .Thank you so much.
