### ISSUE TITLE
NuScenesImVoxelNeck

### ISSUE THREAD

**Issue by Jiayi719** [saic-vul/imvoxelnet#33]
Hello, in the forward function of NuScenesImVoxelNeck you swap x and y dimension as [https://github.com/saic-vul/imvoxelnet/blob/master/mmdet3d/models/necks/imvoxelnet.py#L151](url).
What's the insight of this op?

**Comment by filaPro** [comment]
Hi @Jiayi719 ,
I think we follow the axis order of `Anchor3DHead` which we use from `mmdetection3d` without changes. And it is for some reason designed to accept 2d feature maps in `y, x` coordinates, not `x, y`.

**Comment by Jiayi719** [comment]
OK, thank you. Is there any doc for this in Anchor3DHead?

**Comment by filaPro** [comment]
Not sure where is the best place in the codebase to figure this out. But you can first look [here](https://github.com/saic-vul/imvoxelnet/blob/master/mmdet3d/core/anchor/anchor_3d_generator.py#L158).
