### ISSUE TITLE
Have you tried using the center sampling strategy in nuScene datasets?

### ISSUE THREAD

**Issue by rockywind** [saic-vul/imvoxelnet#35]
Hi,  @filaPro 
I want to use a center sampling strategy in nuScene datasets. Can you give me some advice? Why using center sampling in indoor dataset can improve the mAP?
Thank you for your help in advance!

**Comment by filaPro** [comment]
Hi @rockywind,
You can check FCOS or ATSS in 2d detection about center sampling. Basically is reduces the number of low quality predictions near to the object boundaries. We also adapt it for **our anchor-free 3d** indoor head. However for outdoor datasets we use **well-known anchor-based 2d** head from a couple of detectors in `mmdetection3d`. Most likely in such a setting the head doesn't require center sampling.

**Comment by rockywind** [comment]
Hi @filaPro 
Thank you for your help! I want to use anchor-free 3d outdoor head, so I can use center sampling.
