### ISSUE TITLE
Question about backbone?

### ISSUE THREAD

**Issue by rockywind** [saic-vul/imvoxelnet#36]
Hi, @filaPro 
    When I wanted to change the backbone to resnet18, I modified the [code](https://github.com/saic-vul/imvoxelnet/blob/master/configs/imvoxelnet/imvoxelnet_nuscenes.py). But it ran error!

>   File "/home/CN/zizhang.wu/anaconda3/envs/imvoxelnet_small/lib/python3.7/site-packages/mmcv/utils/registry.py", line 182, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: ImVoxelNet: ResNet: Not implemented yet.

My code is that.
```model = dict(
    type='ImVoxelNet',
    # pretrained='torchvision://resnet50',
    pretrained='torchvision://resnet34',
    backbone=dict(
        type='ResNet',
        depth=34, #50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=False),
        norm_eval=True,
        style='pytorch',
        dcn=dict(type='DCNv2', deform_groups=1, fallback_on_stride=False),
        stage_with_dcn=(False, False, True, True)),```

**Comment by filaPro** [comment]
Hi @rockywind ,

Deformable convolutions are not supprorted for ResNet18 and ResNet34 in `mmdetection`. At least it is true about the version from our Dockerfile. So you can simply remove `dcn` and `stages_with_dcn` from `backbone`. Btw, you should also update `in_channels` in `neck`.

**Comment by rockywind** [comment]
OK @filaPro 
 Thank you very much!
