### ISSUE TITLE
How to make imVoxelNet support multi-classes in nuScenes dataset?

### ISSUE THREAD

**Issue by XinchaoGou** [saic-vul/imvoxelnet#37]
Hi. @filaPro 
Thanks for sharing the code. 
I noticed that your original paper only mentioned results of "car" in nuScenes.
I want to see how it performs under multi-classes. I modified this line to make the network output support 10 classes.
https://github.com/saic-vul/imvoxelnet/blob/3512e89ca98e48aebb21a4c9e9fbe5037220b3a4/configs/imvoxelnet/imvoxelnet_nuscenes.py#L26

I modified it to num_classes=10, 
But still I only get results for single class "car". The other classes are all 0 for mAP. Did you tired this before? Can you help me?

**Comment by filaPro** [comment]
Hi @XinchaoGou ,

We also removed other classes from `NuScenesMultiViewDataset`. To revert them back you also need to comment these [lines](https://github.com/saic-vul/imvoxelnet/blob/master/mmdet3d/datasets/nuscenes_monocular_dataset.py#L29-L35).

Also the performance will be rather poor if we tried only single-scale head for car detection on outdoor KITTI and nuScenes datasets. However for 10 classes it will be much better with 3 [scales](https://github.com/saic-vul/imvoxelnet/blob/3512e89ca98e48aebb21a4c9e9fbe5037220b3a4/configs/_base_/models/hv_pointpillars_fpn_nus.py#L40) as in PointPillars.

**Comment by XinchaoGou** [comment]
Hi @filaPro Thanks a lot for your help! 
I modified the code as you suggested. The experiment is running. By the way, have you ever ran this experiment? Could you share your result for multi-classes as reference?

**Comment by filaPro** [comment]
Probably I tried something like this, but for sure don't have any logs now.

**Comment by XinchaoGou** [comment]
Hi @filaPro , I have the result. but the scores for other classes are very low. What could be the cause? Is it due to the size of anchor? Do you have any suggestions to improve the performance for multi-classes?
![image](https://user-images.githubusercontent.com/35408641/146513272-e7242d79-1cec-4740-8e04-1c2504328c6b.png)

**Comment by filaPro** [comment]
Yes, current [anchors](https://github.com/saic-vul/imvoxelnet/blob/master/configs/imvoxelnet/imvoxelnet_nuscenes.py#L32) are well enogh only for cat category. You need much more scales and [anchors](https://github.com/saic-vul/imvoxelnet/blob/3512e89ca98e48aebb21a4c9e9fbe5037220b3a4/configs/_base_/models/hv_pointpillars_fpn_nus.py#L50-L56) for all classes of nuScenes dataset. For better performance you probably need to redesign `neck` a bit to return feature maps in 3 [levels](https://github.com/saic-vul/imvoxelnet/blob/3512e89ca98e48aebb21a4c9e9fbe5037220b3a4/configs/_base_/models/hv_pointpillars_fpn_nus.py#L40).

**Comment by XinchaoGou** [comment]
Thanks a lot for your help!
