### ISSUE TITLE
Can model inference without "lidar2img" matrix?

### ISSUE THREAD

**Issue by ChenSi521** [saic-vul/imvoxelnet#38]
I have read some your model code, but when I want to inferece by my image, I find I can't create a 'lidar2img' matrix。Can you tell how to inference without 'lidar2img'？

**Comment by filaPro** [comment]
Hi @ChenSi521,

You are right, that for almost all our datasets we assume known intrinsic and extrinsic camera matrices. This is not suprising for outdoor datasets as we know all about sensors at the time they are placed on the vehicle.

The only [model](https://github.com/saic-vul/imvoxelnet/blob/master/configs/imvoxelnet/imvoxelnet_total_sunrgbd_fast.py) that can be run without `lidar2img` is for SUN RGB-D Total3DUnderstanding benchmark. Here we predict camera angles with additional 2d [head](https://github.com/saic-vul/imvoxelnet/blob/master/configs/imvoxelnet/imvoxelnet_total_sunrgbd_fast.py#L18).
