### ISSUE TITLE
Question about the aggregated binary mask

### ISSUE THREAD

**Issue by jianingwangind** [saic-vul/imvoxelnet#39]
Great work and thanks for sharing codes.
I have a question about the aggregated binary mask, specifically according to the paper, the sum will be set to one if the resulting value is 0.
![image](https://user-images.githubusercontent.com/40141805/146738275-cfeab3b7-ce3d-4d21-b587-51c15e899630.png)

But in the codes, i didn't find the corresponding impletation. https://github.com/saic-vul/imvoxelnet/blob/3512e89ca98e48aebb21a4c9e9fbe5037220b3a4/mmdet3d/models/detectors/imvoxelnet.py#L71
here the summed masks are directly used for the average calculation. Could you please give me some insights?

Thanks.

**Comment by filaPro** [comment]
Hi @jianingwangind,

I think in paper we write `1` here to avoid dividing 0 by 0. And in [code](https://github.com/saic-vul/imvoxelnet/blob/3512e89ca98e48aebb21a4c9e9fbe5037220b3a4/mmdet3d/models/detectors/imvoxelnet.py#L74) we set not valid voxel values to zero. If i'm not missing something, it should be the same.

**Comment by jianingwangind** [comment]
Thanks for the reply. 

Assuming that i understand correctly, if you don't set 1 for 0 summing values in advance, the division already return nan before you set invalid voxel values to zeros, which will interrupt the training.

**Comment by filaPro** [comment]
We are getting nan and in the next line replace it with 0, so the overall voxel volume is fine.

**Comment by jianingwangind** [comment]
I see. Thanks for your help.
