### ISSUE TITLE
0 Loss and AP

### ISSUE THREAD

**Issue by alfinnurhalim** [saic-vul/imvoxelnet#41]
Hi. Thank you for your great work! I have successfully trained and tested your model using KITTI dataset and it works.

I currently trying to train a custom dataset (which is not car), but somehow the loss and AP is 0
![image](https://user-images.githubusercontent.com/44990448/147104648-ac70f74a-0383-43b7-8bc6-17cb1bd950a4.png)
I have correctly set the image size and the dataset was already validated and it is good. do you have any suggestion? I might miss some config.

**Comment by alfinnurhalim** [comment]
One more thing, how did you calculate the voxel size? thank you in advance

**Comment by filaPro** [comment]
It's hard to help you, as I don't know your dataset. Looks like the loss is zero. So I think none of your objects are assigned to anchors. You need to check anchor [ranges](https://github.com/saic-vul/imvoxelnet/blob/master/configs/imvoxelnet/imvoxelnet_kitti.py#L30), anchor [sizes](https://github.com/saic-vul/imvoxelnet/blob/master/configs/imvoxelnet/imvoxelnet_kitti.py#L31), [origin](https://github.com/saic-vul/imvoxelnet/blob/master/configs/imvoxelnet/imvoxelnet_kitti.py#L91).

We use voxel size of 0.32m to be the same as a default distance between anchors for point cloud methods on KITTI.

**Comment by alfinnurhalim** [comment]
I see. thank you for the info. let me check it then

**Comment by alfinnurhalim** [comment]
What does [n_voxels](https://github.com/saic-vul/imvoxelnet/blob/3512e89ca98e48aebb21a4c9e9fbe5037220b3a4/configs/imvoxelnet/imvoxelnet_kitti.py#L45) denotes to? how did you calculate it? if you got this from other paper, would you please refer which one?

I'm currently studying your paper, thank you for all your help

**Comment by filaPro** [comment]
`n_voxels` is about `N_x, N_y, N_z` from the paper.

![Screenshot from 2021-12-23 21-52-03](https://user-images.githubusercontent.com/6030962/147281288-ed3cb75a-67c7-4681-b77d-537fa0e72e3c.png)

**Comment by alfinnurhalim** [comment]
Hi, thank you for your answer. I still have several question regarding your paper. I will close this issue and write you an email instead for more detail. thank you

**Comment by alfinnurhalim** [comment]
I'll send to your email written in the paper, is it good?, let me know if you change your email. thank you
