### ISSUE TITLE
can i uesd nuscenes_infos_val.coco.json file  test  iamge? 

### ISSUE THREAD

**Issue by Bincle-Yin** [saic-vul/imvoxelnet#45]
hi，i want used to nuscenes_infos_val.coco.json file  test  iamge，but not nuscenes_infos_val.pkl
e.g. config->_base_->dataset->newxxx.py
```python
    test=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file=data_root + 'nuscenes_infos_val_mono3d.coco.json',
        img_prefix=data_root,
        classes=class_names,
        pipeline=test_pipeline,
        modality=input_modality,
        test_mode=True,
        box_type_3d='Camera'))
evaluation = dict(interval=2)
```
Similar mmdetection3d->config->_base_->dataset->nus-mono3d.py

the idea is ok？

**Comment by filaPro** [comment]
Hi @Bincle-Yin ,

I'm not sure that the idea is ok, as we need 6 images per scene with intrinsic and extrinsic camera matrices. However this json file contains independent images without camera matrices.
