### ISSUE TITLE
no box  is drawed on image

### ISSUE THREAD

**Issue by Calsia** [saic-vul/imvoxelnet#46]
hi，thanks for your code.
when i use it to do detection on my own imgs with shape(2304, 1296). there is some box in model's 'output'. but it can't be drawed on img.
by the way, i useed the multi_scan line.
do you have any suggestion for me?
any reponse will help me a lot

**Comment by Calsia** [comment]
hi，ths for your code.
when i use it to do detection on my own imgs with shape(2304, 1296). there is some box in model's 'output'. but it can't be drawed in img. 
by the way, i useed the multi_scan line.
do you have any suggestion for me? 
any reponsen will help me a lots

**Comment by Calsia** [comment]
besides， is the `extrinsics_mat` needed to do normalize? my world's scale maybe is a little big.  its  unit is mm

**Comment by filaPro** [comment]
It's hard to help you. Which of our models are you using? You need `intrinsic` matrix for all models. And you can run our `TotalSUNRGBD` [model](https://github.com/saic-vul/imvoxelnet/blob/master/configs/imvoxelnet/imvoxelnet_total_sunrgbd_fast.py) without `extrinsic` matrix. Also you can resize your images to our default `640 x 480` [resolution](https://github.com/saic-vul/imvoxelnet/blob/master/configs/imvoxelnet/imvoxelnet_total_sunrgbd_fast.py#L75).

**Comment by Calsia** [comment]
i have tried TotalSUNRGBD, but it also didn't work for me.

i chose the config`imvoxelnet/configs/imvoxelnet/imvoxelnet_scannet_fast.py` ,and i normalize may extrinsics_mat  it into a smale size for the `t`, i get this output. it seems right . but it still looks like not good.

![image](https://user-images.githubusercontent.com/13194457/157596945-e2832cbd-6943-49b5-b9e8-d9ffbdf09510.png)
