### ISSUE TITLE
About gt coordinate in training

### ISSUE THREAD

**Issue by JunjieLiuSWU** [saic-vul/imvoxelnet#47]
Hello, I found that the coordinate of GT boxes is Lidar coordinate, which means the model gets img as input and predicts objects in lidar coordinate. It's very confusing.

**Comment by filaPro** [comment]
Hi @JunjieLiuSWU ,

Don't quite understand your question. This design choice helps us

1) to use KITTI, nuScenes, ScanNet and SUN RGB-D evaluators from `mmdetectoin3d` without changes;
2) use `AnchorHead` from `mmdetection3d` for outdoor dataset without changes.

Overall monocular detection was not supported in `mmdetection3d` at the time we worked on this paper.
