### ISSUE TITLE
resize image will modify intrinsics

### ISSUE THREAD

**Issue by JunjieLiuSWU** [saic-vul/imvoxelnet#48]
Hello, I didn't find anywhere has channged the intrinsics when resize the image, but resize will change intrinsics.

**Comment by filaPro** [comment]
Hi @JunjieLiuSWU ,

You are right, intrinsics are changing while image resizing. It is done [here](https://github.com/saic-vul/imvoxelnet/blob/master/mmdet3d/models/detectors/imvoxelnet.py#L118).

**Comment by JunjieLiuSWU** [comment]
> Hi @JunjieLiuSWU ,
> 
> You are right, intrinsics are changing while image resizing. It is done [here](https://github.com/saic-vul/imvoxelnet/blob/master/mmdet3d/models/detectors/imvoxelnet.py#L118).

Thank you, it;s my careless. I have another question, there are two flip argmumentaions in thre config file: RandomFlip and KittiRandomFlip, how's it? https://github.com/saic-vul/imvoxelnet/blob/master/configs/imvoxelnet/imvoxelnet_kitti.py#L81
https://github.com/saic-vul/imvoxelnet/blob/master/configs/imvoxelnet/imvoxelnet_kitti.py#L89

**Comment by filaPro** [comment]
It will probably be more convenient if image and extrinsics are transformed in the same class. However he we simple call `RandomFlip` from `mmdetection` and then if the image is flipped we also flip extrinsics and bounding boxes in `KittiRandomFlip`.
