### ISSUE TITLE
no works_dir

### ISSUE THREAD

**Issue by Mo-Farazi** [saic-vul/imvoxelnet#50]
Hi.

Thanks for sharing your awesome work! I was wondering where is the "works_dir" for inference ? it is supposed to have the pre-trained models.

**Comment by filaPro** [comment]
Hi @Mo-Farazi ,

You can create `./work_dirs` by yourself in the project root, download models from [here](https://github.com/saic-vul/imvoxelnet/releases) and put them in this directory.

**Comment by Mo-Farazi** [comment]
Unfortunately, they seem to be not correct checkpoint file. I get this error for whichever configs:

FileNotFoundError: ScanNetMultiViewDataset: [Errno 2] No such file or directory: 'data/scannet/scannet_infos_val.pkl'

**Comment by filaPro** [comment]
This error is not about the trained model, it is about ScanNet data preprocessing. Please, follow the installation [link](https://github.com/saic-vul/imvoxelnet/tree/master/data/scannet).
