### ISSUE TITLE
ImVoxelNet SUN RGB-D without the D

### ISSUE THREAD

**Issue by stevengnow** [saic-vul/imvoxelnet#51]
Hello,

I am looking to implement ImVoxelNet on my own custom dataset. (Fantastic work by the way!)
My task is monocular 3D object detection in which the camera (a standard RGB camera) is mounted at an angle (unlike autonomous cars). Because of the change of angle, objects have pitch and roll to account for in addition to the standard yaw angle. Pitch and roll are not taken into account in dataset formats like KITTI. In this way, I would like to try the indoor dataset SUN-RGBD. However, since I do not have a depth camera, I would like to know if there is a way I can "switch off" the D dependence of ImVoxelNet on SUN-RGBD, and if you think this approach will be feasible for my task. Thank you for your time!

**Comment by filaPro** [comment]
Hi @stevengnow ,

Actually ImVoxelNet is a RGB detector either multi-view or single view. So, it does not work with depth or point clouds. And for this reason you should not remove depth :)

**Comment by Steven-m2ai** [comment]
Hello,

Thanks for this reply. Yes since i am doing monocular detection (and single view), so I do not have depth or point cloud data. However, my input data is simply RGB. Do you recommend a way to infer the depth then so I can make it a pseudo-RGBD input for ImVoxelNet?

Please let me know if my question makes any sense. Thank you for your time!

**Comment by filaPro** [comment]
I do not quite understand the question. In case of SUN RGB-D  dataset ImVoxelNet is already a monocular detector. So you do not need depth or pseudo depth, only a single image (and may be camera calibration matrix).

**Comment by Steven-m2ai** [comment]
Oh I see. For some reason I was under the impression that the SUNRGBD dataset holds depth information as well that is used in ImVoxelNet. So in my case with my custom dataset, I can just send in the RGB images, calibration stuff, and ground truth labels in SUNRGBD format right?

**Comment by filaPro** [comment]
Yes, sure.
