### ISSUE TITLE
ImVoxelNet Inference

### ISSUE THREAD

**Issue by Steven-m2ai** [saic-vul/imvoxelnet#53]
Hello,

I wish to run inference on my own dataset. I do not have bounding box labels for any of the objects in the image. However, I do have the camera intrinsics and the Rt matrix. From my understanding this should be all I need. Thus if I want to perform inference, would the easiest way be to create empty label files and run _create_data.py_ before running _test.py_?

**Comment by filaPro** [comment]
Hi @Steven-m2ai ,

You can check [demo](https://github.com/saic-vul/imvoxelnet/tree/master/demo) directory. I didn't try it but looks like there are standalone examples to run on indoor and outdoor datasets.

**Comment by hoangtnm** [comment]
Hi, in the README, there are some visualizations on  `SUN RGB-D` dataset. As I understand this dataset includes RGB images with depth info. Does it mean that this model requires depth information besides RGB images, or only RGB images are enough to run inference? Thanks

**Comment by filaPro** [comment]
Hi @hoangtnm ,
Only a single RGB image and camera parameters.

**Comment by hoangtnm** [comment]
Hi @filaPro, thanks for your response. Given a video or a folder of images, can you share with me how to run inference for ImVoxelNet?

**Comment by filaPro** [comment]
Please follow #55 for camera parameters.
