### ISSUE TITLE
Could you please update the program to run with MMCV 1.5?

### ISSUE THREAD

**Issue by MSTK2014** [saic-vul/imvoxelnet#54]
I installed MMCV 1.5 on my computer, which is a high version for the program. Therefore, too many errors appear, and the program can't run.  Could you please update the program to run with MMCV 1.5?

**Comment by filaPro** [comment]
Hi @MSTK2014 ,

This project heavily relies on `mmdet3d==0.8.0`, for which the required `mmcv` version is `1.3.0`. So updating `mmcv` to `1.5.0` here requires too much work. If you are interested only in our KITTI model you can try ImVoxelNet directly in [mmdetection3d](https://github.com/open-mmlab/mmdetection3d/tree/master/configs/imvoxelnet) with support of `mmcv==1.5.0`. I also have plans to add SUN RGB-D model there but it will take some time.
