### ISSUE TITLE
How to achieve image to voxels projection?

### ISSUE THREAD

**Issue by chendaozai** [saic-vul/imvoxelnet#57]
Hi!, there is a problem about your code. How to achieve image to voxels projection on scannetv2?

**Comment by filaPro** [comment]
Hi @chendaozai ,

I don't quite understand your question. For ScanNet we load extrinsic and intrinsic matrices [here](https://github.com/saic-vul/imvoxelnet/blob/master/mmdet3d/datasets/scannet_monocular_dataset.py#L28), then multiply them to make the projection matrix [here](https://github.com/saic-vul/imvoxelnet/blob/master/mmdet3d/datasets/scannet_monocular_dataset.py#L28) and finally project image features to volxes [here](https://github.com/saic-vul/imvoxelnet/blob/master/mmdet3d/datasets/scannet_monocular_dataset.py#L28).

**Comment by chendaozai** [comment]
Thanks :)
