### ISSUE TITLE
Some problems about val

### ISSUE THREAD

**Issue by wuwangzhuanwan** [saic-vul/imvoxelnet#61]
hello, I find some problems about 'val', I found that there was a problem with the code in line 144 'val_dataset.pipeline = cfg.data.train.pipeline', and it needs to be changed to this val_dataset.pipeline = cfg.data.train.dataset.pipeline. right?

**Comment by filaPro** [comment]
Looks you are right, in case of `RepeatDataset` wrapper. It is kind of `mmdetection3d` bug, as we don't modify this file.

**Comment by wuwangzhuanwan** [comment]
If I want to train 10 classes of detection on the nuscenes dataset, do I just need to change the following two things？
（1）Comment this line： gt_labels_3d[gt_labels_3d > 0] = -1 in mmdet3d/datasets/nuscenes_monocular_dataset.py
（2）Modify this line：num_classes=1==>num_classes=10 in configs/imvoxelnet/imvoxelnet_nuscenes.py
Am I right?  O(∩_∩)O

**Comment by filaPro** [comment]
Basically yes, but the performance will be very low. For better performance you may follow `Anchor3DHead` [parameters](https://github.com/saic-vul/imvoxelnet/blob/master/configs/_base_/models/hv_pointpillars_fpn_nus.py#L51) for NuScenes including sizes, scales and rotations. And for 3 scales here you also need to save 3 2d feature maps from 3 levels of the neck. We use only 1 scale (and 1 output of the neck) if I remember correctly.
