### ISSUE TITLE
Support Three Classes with Kitti Dataset and Be Compatible with Official MMDetection3D

### ISSUE THREAD

**Issue by haibao-yu** [saic-vul/imvoxelnet#62]
**Describe the feature**

We have released a dataset called DAIR-V2X, and we follow your config and mmdetection3d to implement many imvoxelnet benchmarks on our dataset. More details about the dataset can refer to the paper "DAIR-V2X: A Large-Scale Dataset for Vehicle-Infrastructure Cooperative 3D Object Detection", which is accepted by CVPR2022. More details about our benchmark config can refer to https://github.com/AIR-THU/DAIR-V2X/blob/main/configs/sv3d-inf/imvoxelnet/trainval_config.py.

Now, we are trying to make the config compatible with the official mmdetection3d, and make the config support three classes with Kitti format.  But there is large performance fluctuation. So, have you had any related try?

**Comment by filaPro** [comment]
Hi @haibao-yu ,

We tried 3 classes on KITTI at some point (just a very few training runs), but the performance was very low. Mainly because of small sizes of BEV projection of other 2 classes. Btw, official mmdetection3d supports 1 class [benchmark](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/datasets/kitti-3d-car.py).

**Comment by haibao-yu** [comment]
> Hi @haibao-yu ,
> 
> We tried 3 classes on KITTI at some point (just a very few training runs), but the performance was very low. Mainly because of small sizes of BEV projection of other 2 classes. Btw, official mmdetection3d supports 1 class [benchmark](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/datasets/kitti-3d-car.py).

Thanks for your reply. We have collaborated with mmdetection3d to get the proper 3class config. The config is available at https://github.com/AIR-THU/DAIR-V2X/blob/main/configs/sv3d-inf/imvoxelnet/trainval_config.py now.
