### ISSUE TITLE
Directly install saic-vul/imvoxelnet or first install open-mmlab/mmdetection3d? How to replace?

### ISSUE THREAD

**Issue by gyhandy** [saic-vul/imvoxelnet#63]
Hi, I have question about the installation, you mentioned "replacing open-mmlab/mmdetection3d with saic-vul/imvoxelnet", what does this mean? Should we first install mmdetection3d? Or just install saic-vul/imvoxelnet?

Thanks!

**Comment by filaPro** [comment]
Hi @gyhandy ,
We mean, that in the installation guide every time you see `open-mmlab/mmdetection3d` you replace it with `saic-vul/imvoxelnet`.

**Comment by gyhandy** [comment]
Thanks for your reply! When I follow your instruction "Also, [rotated_iou](https://github.com/lilanxiao/Rotated_IoU) should be installed with [these](https://github.com/saic-vul/imvoxelnet/blob/master/docker/Dockerfile#L31-L34) 4 commands."
(1) It shows the following errors, while my cuda version is not 10.1, is the version a hard coding one? 
"error: [Errno 2] No such file or directory: '/usr/local/cuda-10.1/bin/nvcc': '/usr/local/cuda-10.1/bin/nvcc'"
(2) Should I also replace the "mmdetection3d" with "imvoxelnet" when I install rotated_iou?

Thank you in advance for your help!

**Comment by filaPro** [comment]
(1) It should be fine with cuda 10.1. Can you please try with out Dockerfile?
(2) No.

Btw it you are interested only in KITTI or SUN RGB-D results, you can try ImVoxelNet directly in [mmdetection3d](https://github.com/open-mmlab/mmdetection3d/tree/master/configs/imvoxelnet).

**Comment by gyhandy** [comment]
Yes, I am interested in the SUN RGB-D results. Do you mean that I only need the official mmdetection3d code and do not need to use your code if I only want to reproduce the  SUN RGB-D results? Thanks!

**Comment by filaPro** [comment]
Yes, I've contributed our models to their codebase a couple of months ago.

**Comment by gyhandy** [comment]
Hi Danila,

Thank you for your excellent work! If I want to un single view detection on
ScanNet, are there any suggestions on code modification? Thanks!

Best,
Yunhao

Yunhao (Andy) Ge

CS Ph.D. Candidate at USC

Website: gyhandy.github.io

Email: ***@***.***

Tel：1-2136759836

3551 Trousdale Pkwy, University Park, Los Angeles, United States
