### ISSUE TITLE
Collaboration with MMDetection3D

### ISSUE THREAD

**Issue by Tai-Wang** [saic-vul/imvoxelnet#7]
Hi, developers of ImVoxelNet,

Glad to see your insightful project is implemented based on MMDetection3D! Actually, multi-view image based 3D detection and a general detector could handle both indoor and outdoor scenes are also part of the original motivation to develop MMDetection3D. Great to see you take a step forward toward general 3D detection.

I would like to ask if there is any plan to contribute an implementation of ImVoxelNet to [MMDetection3D](https://github.com/open-mmlab/mmdetection3d)? If so, maybe we can have a detailed discussion about it? Please feel free to ask if there is any help needed from MMDet3D team.

On behalf of the MMDet3D Development Team

Best,
Tai

**Comment by filaPro** [comment]
Hi, @Tai-Wang 

First, I would like to thank you again for your incredible work on the mmdetection3d. In fact, your FCOS3D is not least general-propose compared to ImVoxelNet. Also thanks for your interest in our work. It would be an honor for me to contribute to mmdetection3d. I think, I can close this issue and open a new one in mmdetection3d repo.

**Comment by Tai-Wang** [comment]
Hi @filaPro ,

No problem. I am also working for some advancements (and have made some progress) on image-based 3D detection based on FCOS3D, and we do hope to push it forward with our codebase in the near future, so I believe your work could bring good insights.

Please feel free to open new issues or PRs in mmdetection3d repo if needed. Many thanks for your contributions~
