### ISSUE TITLE
Questions about some details of the paper

### ISSUE THREAD

**Issue by Marigod98** [saic-vul/imvoxelnet#9]
Questions about some details of the paper

**Comment by Marigod98** [comment]
Hi, Thanks for the great work.
Just a little confused，For indoor datasets, such as SUNRGBD, I think the process of projecting 2d feature into 3D voxel volumes is similar to the process of transforming RGBD images to point clouds and then voxelization，because both use  camera model to transform, is it correct?

**Comment by filaPro** [comment]
Hi @Marigod98 ,
If I understand you correctly, you are right.
JFYI, we do not use depth channel and for `Total3DUnderstanding` [benchmark](https://github.com/saic-vul/imvoxelnet/blob/master/configs/imvoxelnet/imvoxelnet_total_sunrgbd.py) we even do not use camera pose.

**Comment by Marigod98** [comment]
@filaPro Thanks very much for your answer!
